const fs = require('fs');
const assert = require('assert/strict');
const path = require('node:path');
const os = require('node:os');
const {chromium} = require('playwright');
const source = fs.readFileSync(path.join(__dirname, '../mini apps/Event Guest Manager/RefMonitor.php'),'utf8').replace(/\r\n/g, '\n');
const palette = JSON.parse(fs.readFileSync(path.join(__dirname,'../api/lib/egm-refmonitor-teams.php'),'utf8').match(/const EGM_REF_COVER_COLORS = (\[.*?\]);/)[1].replace(/'/g, '\"'));
const game = {id:'1234567890abcdef',name:'بازی مسیر صعود',has_levels:true,auto_room_manager:true,require_cover_color:false,no_score_needed:false,min_players:1,max_players:5,levels:[{id:'level1',name:'مرحله اول'},{id:'level2',name:'مرحله دوم'}]};
let submissions = 0;
let manual = false;
let requireColor = false;
let noScore = false;
let single = false;
let completions = 0;
let team = {id:1,name:'تیم امید',members:[{id:1,name:'علی رضایی'}],started_at:'2026-10-06',ended_at:null,scores:{},total_score:0,can_edit_members:false,room_assignment:{level_id:'level1',level_name:'مرحله اول',room_name:'اتاق آفتاب'},waiting_for_room:false};
let script = source.match(/<script nonce=.*>([\s\S]*?)<\/script>/)[1].replace(/<\?= json_encode\(\$games,[\s\S]*?\?>/,JSON.stringify([game])).replace(/<\?= json_encode\(\$activePeriod,[\s\S]*?\?>/,JSON.stringify({code:'001',title:'بازه اول'})).replace(/<\?= json_encode\(\$_SESSION\['ref_monitor_csrf'\],[\s\S]*?\?>/,'"test"');
script = script.replace(/<\?= json_encode\(EGM_REF_COVER_COLORS,[\s\S]*?\?>/,JSON.stringify(palette));
let markup = source.slice(source.indexOf('<div class="main-area" data-ref-view="home">'),source.indexOf('  <?php endif; ?>\n</section></main>')).replace(/<\?[\s\S]*?\?>/g,'').replace('data-open-game=""','data-open-game="1234567890abcdef"');
const style = [...source.matchAll(/<style nonce=.*>([\s\S]*?)<\/style>/g)].map(match=>match[1]).join('\n');
const dialog = source.match(/<dialog[\s\S]*?<\/dialog>/g).join('');
const header = source.match(/<header class="topbar">[\s\S]*?<\/header>/)[0].replace('<?= $escape($adminDisplayName) ?>','محمد رضایی').replace(/<\?[\s\S]*?\?>/g,'');
const html = `<html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${style}</style><main class="app"><section class="phone">${header}${markup}</section></main>${dialog}<script>${script}</script></html>`;
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try {
 const page=await browser.newPage({viewport:{width:390,height:844}});
 await page.addInitScript(()=>{
   window.testDingNotes=0;window.testSoundEnd=0;window.testCancelledNotes=0;
   window.AudioContext=class{state='running';currentTime=0;destination={};async resume(){}createOscillator(){return {frequency:{value:0},connect(){},start(){window.testDingNotes++},stop(time){if(time===undefined)window.testCancelledNotes++;else window.testSoundEnd=Math.max(window.testSoundEnd,time)}}}createGain(){return {gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}}}};
   if('Notification'in window)Notification.requestPermission=async()=>'denied';
 });
 const fill=async(selector,value)=>{await page.waitForFunction(()=>!document.querySelector('#ref-loader').open);await page.locator(selector).fill(value);};
 const errors=[];page.on('pageerror', e=>errors.push(e.message));
 await page.route('http://ref.test/**',route=>{
 const req=route.request();
 if(req.method()==='POST'){
 const action=new URLSearchParams(req.postData()).get('action');
 if(action==='create_team') {const fields=new URLSearchParams(req.postData()); team={...team,can_edit_members:true,name:fields.get('name'),cover_color:fields.get('cover_color')||'',started_at:null,ended_at:null,room_assignment:null,waiting_for_room:false,scores:{}};}
 if(action==='update_team_details') {const fields=new URLSearchParams(req.postData());team={...team,name:fields.get('name'),cover_color:fields.get('cover_color')};}
 if(action==='start_team') team={...team,started_at:'2026-10-06',waiting_for_room:false,room_assignment:{level_id:'level1',level_name:'مرحله اول',room_name:'اتاق آفتاب'}};
 if(action==='complete_level') {
 const fields = new URLSearchParams(req.postData());
 assert.equal(fields.has('score'),false);
 completions++;
 const scores = {...team.scores,[fields.get('level_id')]:{score:null,completion_only:true}};
 const ended = Object.keys(scores).length >= (single ? 1 : 2);
 team={...team,scores,ended_at:ended?'2026-10-07':null,room_assignment:(!manual&&!ended)?{level_id:'level2',level_name:'مرحله دوم',room_name:'اتاق باران'}:null};
}
 if(action==='submit_score') {
 submissions++;
 const fields=new URLSearchParams(req.postData());
 team={...team,total_score:team.total_score+Number(fields.get('score')),scores:{...team.scores,[fields.get('level_id')]:{score:Number(fields.get('score'))}},room_assignment:null,waiting_for_room:submissions===1,ended_at:submissions===2?'2026-10-06':null};
 }
 return route.fulfill({contentType:'application/json',body:JSON.stringify({status:'ok',teams:[team],team,invitees:[{id:1,name:'علی رضایی',work_id:'1',...team.members[0]}],period_code:'001'})});
 }
 if(req.url().endsWith('RefMonitor.php'))return route.fulfill({contentType:'text/html;charset=utf-8',body:(manual ? html.replace('"auto_room_manager":true', '"auto_room_manager":false') : html).replace('"require_cover_color":false', '"require_cover_color":'+requireColor).replace('"no_score_needed":false','"no_score_needed":'+noScore).replace('"has_levels":true','"has_levels":'+!single)});
 const font=req.url().split('/').pop();
 const fontPath=path.join(__dirname, '../style/fonts', font);
 if(fs.existsSync(fontPath))return route.fulfill({body:fs.readFileSync(fontPath),contentType:'font/woff2'});
 if(req.url().endsWith('/assets/hamrah-icon.svg'))return route.fulfill({body:fs.readFileSync(path.join(__dirname,'../assets/hamrah-icon.svg')),contentType:'image/svg+xml'});
 return route.fulfill({status:404,body:''});
 });
 await page.goto('http://ref.test/RefMonitor.php');
 await page.locator('#ref-room-alerts').click();await page.waitForFunction(()=>!document.querySelector('#ref-room-alerts').disabled);
 await page.locator('[data-open-game]').click();await page.locator('#ref-teams-list button').click();
 await page.locator('#ref-room-card .room-name').waitFor();
 assert.equal(await page.locator('#ref-room-card .room-name').textContent(),'اتاق آفتاب');
 assert.match(await page.locator('#ref-room-card').evaluate(el=>getComputedStyle(el).backgroundImage),/linear-gradient/);
 assert.equal(await page.locator('#ref-room-card .room-name').evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');
 assert.match(await page.locator('#ref-room-card').evaluate(el=>getComputedStyle(el).animationName),/room-gradient/);
 assert.equal(await page.locator('.topbar').evaluate(el=>getComputedStyle(el).backgroundImage),'none');
 assert.equal(await page.locator('.brand-icon-badge svg path').count(),1);
 assert.equal(await page.locator('.welcome-name').evaluate(el=>getComputedStyle(el).color),'rgb(0, 118, 173)');
 assert.equal(await page.locator('h1.welcome').evaluate(el=>getComputedStyle(el).color),'rgb(32, 37, 44)');
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('#ref-member-section').evaluate(el=>el.tagName),'SECTION');
 assert.ok(await page.locator('#ref-detail-members').isVisible());
 for (const size of [{width:320,height:568},{width:390,height:667},{width:460,height:844}]) {
   await page.setViewportSize(size);
   assert.ok(await page.locator('[data-ref-view="team-detail"]').evaluate(el=>el.scrollHeight<=el.clientHeight+1),`Team page scrolls at ${size.width}x${size.height}`);
 }
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.locator('#ref-detail-members').isVisible());
 assert.ok(await page.locator('#ref-room-card .room-name').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))>=32);
 await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})))); await page.screenshot({path:path.join(os.tmpdir(), 'ref-room-detail.png')});
 await page.locator('#ref-open-scores').click();
 await page.locator('#ref-rounds-total').waitFor();
 assert.match(await page.locator('#ref-score-stage').textContent(),/۱۰ \+ ۱۵ \+ ۲۰ = ۴۵/);
 await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})))); await page.screenshot({path:path.join(os.tmpdir(), 'ref-room-score.png')});
 for(const width of [320,390,460]){
 await page.setViewportSize({width,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 }
 team={...team,room_assignment:null,waiting_for_room:true};
 await page.locator('#ref-back').click();
 await page.waitForFunction(()=>document.querySelector('#ref-room-card').textContent.includes('در انتظار اتاق'));
 assert.ok(await page.locator('#ref-open-scores').isHidden());
 await page.evaluate(()=>window.testDingNotes=0);
 team={...team,room_assignment:{level_id:'level1',level_name:'مرحله اول',room_id:'room-live',room_name:'اتاق زنده',assigned_at:'2026-10-07T12:00:00'},waiting_for_room:false};
 await page.waitForFunction(()=>document.querySelector('#ref-room-card').textContent.includes('اتاق زنده'));
 assert.equal(await page.locator('#ref-loader').evaluate(el=>el.open),false);
 assert.ok(await page.locator('#ref-open-scores').isVisible());
 assert.equal(await page.evaluate(()=>window.testDingNotes),9);
 assert.equal(await page.locator('#ref-room-arrival').evaluate(el=>el.open),true);
 assert.equal(await page.locator('[data-arrival-room]').textContent(),'اتاق زنده');
 assert.ok(await page.evaluate(()=>window.testSoundEnd>=5.6&&window.testSoundEnd<8),'Room attention sound must last about six seconds');
 await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>window.testDingNotes),9);
 await page.getByRole('button',{name:'متوجه شدم، می‌رویم'}).click();
 await page.waitForFunction(()=>window.testCancelledNotes>=9);
 assert.equal(await page.locator('#ref-room-arrival').evaluate(el=>el.open),false);
 team={...team,room_assignment:null,waiting_for_room:true};
 await page.waitForFunction(()=>document.querySelector('#ref-room-card').textContent.includes('در انتظار اتاق'));
 console.log('One-second team polling assigns rooms without refresh or loader and tracks room release.');
 assert.equal(errors.length,0,errors.join('\n'));
  await page.locator('#ref-back').click();
 await page.locator('#ref-new-team').click();
 await fill('#ref-team-name','تیم جدید');
 await page.locator('#ref-team-next-name').click();
 await fill('#ref-search-input','علی');
 await page.locator('#ref-search-results button').first().waitFor();
 assert.equal(await page.locator('#ref-loader').evaluate(el=>el.open),false);
 await page.locator('#ref-search-results button').first().click();
 await page.locator('#ref-team-next-members').click();
 await page.locator('#ref-submit-team').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="team-detail"]').classList.contains('hidden'));
 await page.locator('#ref-back').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="game"]').classList.contains('hidden'));
 assert.ok(!source.includes('🎮'));
 console.log('Team creation opens detail directly; Back returns to game; controller emoji removed.');
  team={...team,started_at:null,ended_at:null,waiting_for_room:false,room_assignment:null,scores:{}};
 await page.goto('http://ref.test/RefMonitor.php');
 await page.locator('[data-open-game]').click();
 await page.locator('#ref-teams-list button').waitFor();
 assert.match(await page.locator('#ref-teams-list').textContent(),/آماده شروع/);
 assert.equal(await page.locator('#ref-team-filter').count(),0);
 assert.equal(await page.locator('#ref-teams-status').textContent(),'');
 assert.equal(await page.locator('.team-group-title').first().textContent(),'آماده شروع');
 await page.locator('#ref-teams-list button').click();
 await page.locator('#ref-start-team').click();
 await page.locator('#ref-room-card .room-name').waitFor();
 await page.locator('#ref-open-scores').click();
 await fill('#ref-rounds-total','45');
 await page.locator('#ref-score-submit').click();
 assert.ok(await page.locator('#ref-score-confirm').isVisible());
 await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})))); await page.screenshot({path:path.join(os.tmpdir(), 'ref-score-confirm.png')});
 assert.match(await page.locator('#ref-confirm-room').textContent(),/اتاق آفتاب/);
 assert.match(await page.locator('#ref-confirm-score').textContent(),/45/);
 await page.locator('#ref-confirm-cancel').click();
 assert.equal(submissions,0);
 await page.locator('#ref-score-submit').click();
 await page.locator('#ref-confirm-save').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="team-detail"]').classList.contains('hidden'));
 assert.equal(submissions,1);
 assert.match(await page.locator('#ref-room-card').textContent(),/در انتظار اتاق/);
 await page.locator('#ref-edit-name').click();
 await fill('#ref-detail-name','ویرایش در حال انجام');
 team={...team,waiting_for_room:false,room_assignment:{level_id:'level2',level_name:'مرحله دوم',room_name:'اتاق باران'}};
 await page.waitForFunction(()=>document.querySelector('#ref-room-card').textContent.includes('اتاق باران'));
 assert.match(await page.locator('#ref-room-card').textContent(),/اتاق باران/);
 assert.equal(await page.locator('#ref-detail-name').inputValue(),'ویرایش در حال انجام');
 await page.locator('#ref-edit-cancel').click();
 if(await page.locator('#ref-room-arrival').evaluate(el=>el.open))await page.getByRole('button',{name:'متوجه شدم، می‌رویم'}).click();
 await page.locator('#ref-open-scores').click();
 await fill('#ref-rounds-total','70');
 await page.locator('#ref-score-submit').click();
 await page.locator('#ref-confirm-save').click();
 await page.locator('#ref-completion-card').waitFor({state:'visible'});
 assert.match(await page.locator('#ref-completion-score').textContent(),/115/);
 assert.ok(await page.locator('#ref-detail-home').isHidden());
 assert.ok(await page.locator('#ref-completion-back').isVisible());
 assert.equal(await page.locator('#ref-completion-back').evaluate(el=>el.parentElement.id),'ref-detail-dock');
 await page.locator('#ref-completion-back').click();await page.locator('#ref-back').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="home"]').classList.contains('hidden'));
 await page.locator('[data-open-game]').click();
 await page.locator('#ref-teams-list button').waitFor();
 assert.match(await page.locator('#ref-teams-list').textContent(),/پایان‌یافته/);
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('No search or team counts, grouped states, start, score confirmation/cancel, waiting, next room and completion journeys passed.');
  manual = true;
 team={...team,ended_at:null,room_assignment:null,waiting_for_room:false,scores:{}};
 await page.goto('http://ref.test/RefMonitor.php');
 await page.locator('[data-open-game]').click();
 await page.locator('#ref-teams-list button').click();
 await page.locator('#ref-open-scores').click();
 assert.ok(await page.locator('[data-ref-view="score"]').isHidden());
 await fill('#ref-score-form input','25');
 await page.locator('#ref-score-submit').click();
 assert.match(await page.locator('#ref-confirm-room').textContent(),/مرحله اول/);
 await page.locator('#ref-confirm-cancel').click();
 assert.equal(submissions,2);
 await page.locator('#ref-score-submit').click();
 await page.locator('#ref-confirm-save').click();
 await page.waitForFunction(()=>document.querySelector('#ref-score-form')?.dataset.levelId==='level2');
 assert.equal(submissions,3);
 assert.ok(await page.locator('#ref-score-form input').isVisible());
 await page.locator('#ref-back').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="team-detail"]').classList.contains('hidden'));
 await page.locator('#ref-back').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="game"]').classList.contains('hidden'));
 await page.locator('#ref-back').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="home"]').classList.contains('hidden'));
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Manual scoring opens entry directly, supports confirmation cancellation and advances to the next stage.');
  requireColor = true; manual = false;
 await page.goto('http://ref.test/RefMonitor.php');
 await page.locator('[data-open-game]').click();
 await page.locator('#ref-new-team').click();
 await fill('#ref-team-name','تیم رنگی');
 await page.locator('#ref-team-next-name').click();
 assert.ok(await page.locator('[data-team-step="name"]').isVisible());
 assert.equal(await page.locator('#ref-team-cover-color').evaluate(el=>el.tagName),'SELECT');
 assert.equal(await page.locator('#ref-team-cover-color option').count(),19);
 await page.locator('#ref-team-cover-color + .cover-trigger').click();
 assert.equal(await page.locator('#ref-color-picker [role=option]').count(),18);
 assert.ok(await page.locator('.cover-color-options').evaluate(el=>el.scrollHeight>el.clientHeight));
 assert.ok(await page.locator('#ref-color-picker').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));
 assert.equal(await page.locator('#ref-color-picker').evaluate(el=>getComputedStyle(el).fontFamily),await page.locator('body').evaluate(el=>getComputedStyle(el).fontFamily));
 await page.locator('#ref-color-picker [role=option]').filter({hasText:/^آبی$/}).click();
 assert.equal(await page.locator('#ref-team-cover-color').inputValue(),'آبی');
 await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})))); await page.screenshot({path:path.join(os.tmpdir(),'ref-cover-picker.png')});
 await page.locator('#ref-team-next-name').click();
 await fill('#ref-search-input','علی');
 await page.locator('#ref-search-results button').first().click();
 await page.locator('#ref-team-next-members').click();
 assert.match(await page.locator('#ref-review-cover').textContent(),/آبی/);
 await page.locator('#ref-submit-team').click();
 await page.waitForFunction(()=>document.querySelector('#ref-detail-cover').textContent.includes('آبی'));
 assert.equal(team.cover_color,'آبی');
 await page.locator('#ref-edit-name').click();
 assert.ok(await page.locator('#ref-team-edit').isVisible());
 await fill('#ref-detail-name','تیم نهایی');
 await page.locator('#ref-detail-cover-input + .cover-trigger').click();
 await page.locator('#ref-color-picker [role=option]').filter({hasText:/^قرمز$/}).click();
 await page.locator('#ref-edit-save').click();
 await page.waitForFunction(()=>document.querySelector('#ref-detail-cover').textContent.includes('قرمز'));
 assert.equal(team.name,'تیم نهایی');
 await page.locator('#ref-edit-name').click();
 await fill('#ref-detail-name','نام لغوشده');
 await page.locator('#ref-edit-cancel').click();
 assert.equal(team.name,'تیم نهایی');
 await page.locator('#ref-edit-name').click();
 await page.locator('#ref-edit-members').click();
 await page.locator('#ref-team-next-members').click();
 await page.locator('#ref-submit-team').click();
 await page.waitForFunction(()=>!document.querySelector('[data-ref-view="team-detail"]').classList.contains('hidden'));
 await page.locator('#ref-start-team').click();
 await page.locator('#ref-room-card .room-name').waitFor();
 await page.locator('#ref-open-scores').click();
 await fill('#ref-rounds-total','20');
 await page.locator('#ref-score-submit').click();
 assert.match(await page.locator('#ref-confirm-team').textContent(),/قرمز/);
 await page.locator('#ref-confirm-cancel').click();
 for(const width of [320,390,460]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('18-color dropdown, required selection, combined pencil edits, edit cancellation and member editing passed.');
  noScore = true;
 for (const mode of [{manual:true,single:false},{manual:false,single:false},{manual:true,single:true}]) {
   manual = mode.manual; single = mode.single;
   team={...team,started_at:null,ended_at:null,scores:{},room_assignment:null,waiting_for_room:false};
   await page.goto('http://ref.test/RefMonitor.php');
   await page.locator('[data-open-game]').click();
   await page.locator('#ref-teams-list button').click();
   await page.locator('#ref-start-team').click();
   await page.waitForFunction(()=>!document.querySelector('#ref-open-scores').classList.contains('hidden'));
   assert.equal(await page.locator('#ref-open-scores').textContent(),single?'پایان بازی':'پایان مرحله');
   await page.locator('#ref-open-scores').click();
   assert.equal(await page.locator('#ref-confirm-title').textContent(),single?'تأیید پایان بازی':'تأیید پایان مرحله');
   assert.equal(await page.locator('#ref-score-confirm input').count(),0);
   const before = completions;
   await page.locator('#ref-confirm-cancel').click();
   assert.equal(completions,before);
   await page.locator('#ref-open-scores').click();
   await page.locator('#ref-confirm-save').click();
   await page.waitForFunction(()=>!document.querySelector('#ref-score-confirm').open);
   assert.equal(completions,before+1);
   assert.equal(Object.values(team.scores)[0].score,null);
   assert.ok(await page.locator('#ref-total-score').isHidden());
   if (!single) {
     if (!manual) assert.equal(await page.locator('#ref-room-card .room-name').textContent(),'اتاق باران');
     await page.locator('#ref-open-scores').click();
     assert.match(await page.locator('#ref-confirm-room').textContent(),/مرحله دوم/);
     await page.locator('#ref-confirm-save').click();
   }
   await page.locator('#ref-completion-card').waitFor({state:'visible'});
   assert.ok(await page.locator('#ref-completion-score').isHidden());
   assert.ok(await page.locator('#ref-detail-home').isHidden());assert.ok(await page.locator('#ref-completion-back').isVisible());
 }
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('No-score manual/automatic stages and single games require confirmation, cancel safely, advance and finish without score input.');
 noScore=false;manual=true;single=false;requireColor=false;
 for(const [tone,message] of [['walk-in','به دلیل ورود خارج از برنامه ممکن است این فرد شامل جایزه نشود'],['past','به دلیل حضور در مسابقات گذشته شامل جایزه نمی شود'],['','']]) {
   team={...team,started_at:null,ended_at:null,scores:{},room_assignment:null,members:[{id:1,name:'علی رضایی',work_id:'1',prize_warning_tone:tone,prize_warning:message}]};
   await page.goto('http://ref.test/RefMonitor.php');
   await page.locator('[data-open-game]').click();await page.locator('#ref-teams-list button').click();
   await page.locator('#ref-detail-members').waitFor({state:'visible'});
   assert.equal(await page.locator('#ref-detail-members .prize-warning').count(),message?1:0);
   if(message)assert.equal(await page.locator('#ref-detail-members .prize-warning').textContent(),message);
   await page.locator('#ref-back').click();await page.locator('#ref-new-team').click();
   await fill('#ref-team-name','تیم هشدار');await page.locator('#ref-team-next-name').click();
   await fill('#ref-search-input','علی');await page.locator('#ref-search-results button').first().waitFor();
   assert.ok(await page.locator('#ref-search-results button').first().isEnabled());
   assert.equal(await page.locator('#ref-search-results .prize-warning').count(),message?1:0);
   await page.locator('#ref-search-results button').first().click();
   assert.equal(await page.locator('#ref-selected-list .prize-warning').count(),message?1:0);
   await page.locator('#ref-team-next-members').click();
   assert.equal(await page.locator('#ref-review-members .prize-warning').count(),message?1:0);
   await page.locator('#ref-submit-team').click();await page.locator('#ref-detail-members').waitFor({state:'visible'});
   if(tone){await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(os.tmpdir(),`ref-prize-${tone}.png`)});}
 }
 console.log('Walk-in and previous-game warnings appear in search, selection, review and team details without blocking creation; approved guests have no warning.');
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('#ref-room-card').evaluate(el=>getComputedStyle(el).animationName),'none');
 assert.equal(await page.locator('[data-ref-view="score-entry"]').evaluate(el=>getComputedStyle(el).animationName),'none');
 console.log('Blue gradient room guidance, always-visible members and reduced-motion preferences passed.');
 console.log('Room detail, score guidance, 320/390/460px layouts, waiting state and console checks passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
